site_name: Draughts
nav:
  - Home: index.md
  - Contributers: contributers.md
  - Setup: setup.md
  - Game: game.md
  - Time Complexity: timecomplexity.md
  - Modules: modules.md

theme:
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true
  highlightjs: true
  hljs_languges:
    - python
  nav_style: dark